baseURL = "[https://ggus39.github.io/xiang/](https://ggus39.github.io/xiang/)"
languageCode = "zh-cn"
title = "如此小生"
theme = "PaperMod"
[[menu.main]]
    name = "记录一下自己的一点bo"
    url = "/records/"
    weight = 10

[[menu.main]]
    name = "想要的习惯"
    url = "/habits/"
    weight = 20

[[menu.main]]
    name = "痛的想"
    url = "/thought/"
    weight = 30